# +------------------------------------------------------+ #
# |                   Scape's Notice                     | #
# +------------------------------------------------------+ #

# Credits to the orginal authors of essentials!
# SupremeCore was only built of Essentials(First version) Config with may adjustments and improvements.
# [!] No essentials code was used in SupremeCore.

# SupremeCore was made to for fill server owners needs.

############################################################
# +------------------------------------------------------+ #
# |                    sCore (Global)                    | #
# +------------------------------------------------------+ #
############################################################

player:

  # A color code between 0-9 or a-f. Set to 'none' to disable.
  ops-name-color: '4'

  # The character(s) to prefix all nicknames, so that you know they are not true usernames.
  nickname-prefix: '~'

  # The maximum length allowed in nicknames. The nickname prefix is included in this.
  max-nick-length: 15

  # Disable this if you have any other plugin, that modifies the displayname of a user.
  change-displayname: true

  # When this option is enabled, the (tab) player list will be updated with the displayname.
  # The value of change-displayname (above) has to be true.
  change-playerlist: true

  # When EssentialsChat.jar isn't used, force essentials to add the prefix and suffix from permission plugins to displayname.
  # This setting is ignored if EssentialsChat.jar is used, and defaults to 'true'.
  # The value of change-displayname (above) has to be true.
  # Do not edit this setting unless you know what you are doing!
  add-prefix-suffix: false

teleport:

  # If the teleport destination is unsafe, should players be teleported to the nearest safe location?
  # If this is set to true, Essentials will attempt to teleport players close to the intended destination.
  # If this is set to false, attempted teleports to unsafe locations will be cancelled with a warning.
  teleport-safety: true

  # The delay, in seconds, required between /home, /tp, etc.
  teleport-cooldown: 0

  # The delay, in seconds, before a user actually teleports.  If the user moves or gets attacked in this timeframe, the teleport never occurs.
  teleport-delay: 0

  # The delay, in seconds, a player can't be attacked by other players after they have been teleported by a command.
  # This will also prevent the player attacking other players.
  teleport-invulnerability: 4

other:

  # The delay, in seconds, required between /heal or /feed attempts.
  heal-cooldown: 60

  # Disabling commands here will prevent Essentials handling the command, this will not affect command conflicts.
  # You should not have to disable commands used in other plugins, they will automatically get priority.
  # See http://wiki.bukkit.org/Commands.yml#aliases to map commands to other plugins.
  disabled-commands:
  #  - nick
  #  - clear

  # These commands will be shown to players with socialSpy enabled.
  # You can add commands from other plugins you may want to track or
  # remove commands that are used for something you dont want to spy on.
  # Set - '*' in order to listen on all possible commands.
  socialspy-commands:
    - msg
    - w
    - r
    - mail
    - m
    - t
    - whisper
    - emsg
    - tell
    - er
    - reply
    - ereply
    - email
    - action
    - describe
    - eme
    - eaction
    - edescribe
    - etell
    - ewhisper
    - pm

  # Sort output of /list command by groups.
  # You can hide and merge the groups displayed in /list by defining the desired behaviour here.
  # Detailed instructions and examples can be found on the wiki: http://wiki.ess3.net/wiki/List
  list:
    # To merge groups, list the groups you wish to merge
    #Staff: owner admin moderator
    Admins: owner admin
    # To limit groups, set a max user limit
    #builder: 20
    # To hide groups, set the group as hidden
    #default: hidden
    # Uncomment the line below to simply list all players with no grouping
    #Players: '*'

  # Turn off god mode when people leave the server.
  remove-god-on-disconnect: false

  afk:
    # Auto-AFK
    # After this timeout in seconds, the user will be set as AFK.
    # This feature requires the player to have essentials.afk.auto node.
    # Set to -1 for no timeout.
    auto-afk: 300

    # Auto-AFK Kick
    # After this timeout in seconds, the user will be kicked from the server.
    # essentials.afk.kickexempt node overrides this feature.
    # Set to -1 for no timeout.
    auto-afk-kick: -1

    # Auto-AFK Pool
    # after the auto-afk timeout, the user will be placed into the afk pool.
    auto-afk-pool: false

    # Set this to true, if you want to freeze the player, if the player is AFK.
    # Other players or monsters can't push the player out of AFK mode then.
    # This will also enable temporary god mode for the AFK player.
    # The player has to use the command /afk to leave the AFK mode.
    freeze-afk-players: false

    # When the player is AFK, should he be able to pickup items?
    # Enable this, when you don't want people idling in mob traps.
    disable-item-pickup-while-afk: false

    # This setting controls if a player is marked as active on interaction.
    # When this setting is false, the player would need to manually un-AFK using the /afk command.
    cancel-afk-on-interact: true

    # Should we automatically remove afk status when a player moves?
    # Player will be removed from AFK on chat/command regardless of this setting.
    # Disable this to reduce server lag.
    cancel-afk-on-move: true

  # You can disable the death messages of Minecraft here.
  death-messages: true

  # Should players with permissions be able to join and part silently?
  # You can control this with essentials.silentjoin and essentials.silentquit permissions if it is enabled.
  # In addition, people with essentials.silentjoin.vanish will be vanished on join.
  allow-silent-join-quit: false

  # Add worlds to this list, if you want to automatically disable god mode there.
  no-god-in-worlds:
  #  - world_nether

  # Set to true to enable per-world permissions for teleporting between worlds with essentials commands.
  # This applies to /world, /back, /tp[a|o][here|all], but not warps.
  # Give someone permission to teleport to a world with essentials.worlds.<worldname>
  # This does not affect the /home command, there is a separate toggle below for this.
  world-teleport-permissions: false

  # The number of items given if the quantity parameter is left out in /item or /give.
  # If this number is below 1, the maximum stack size size is given. If over-sized stacks.
  # are not enabled, any number higher than the maximum stack size results in more than one stack.
  default-stack-size: -1

  # Over-sized stacks are stacks that ignore the normal max stack size.
  # They can be obtained using /give and /item, if the player has essentials.oversizedstacks permission.
  # How many items should be in an over-sized stack?
  oversized-stacksize: 64

  # Allow repair of enchanted weapons and armor.
  # If you set this to false, you can still allow it for certain players using the permission.
  # essentials.repair.enchanted
  repair-enchanted: true

  # Allow 'unsafe' enchantments in kits and item spawning.
  # Warning: Mixing and overleveling some enchantments can cause issues with clients, servers and plugins.
  unsafe-enchantments: false

  #Do you want Essentials to keep track of previous location for /back in the teleport listener?
  #If you set this to true any plugin that uses teleport will have the previous location registered.
  register-back-in-listener: false

  #Delay to wait before people can cause attack damage after logging in.
  login-attack-delay: 5

  #Set the max fly speed, values range from 0.1 to 1.0
  max-fly-speed: 0.8

  #Set the max walk speed, values range from 0.1 to 1.0
  max-walk-speed: 0.8

  #Set the maximum amount of mail that can be sent within a minute.
  mails-per-minute: 1000

  # Set the maximum time /tempban can be used for in seconds.
  # Set to -1 to disable, and essentials.tempban.unlimited can be used to override.
  max-tempban-time: -1

  # Should sCore enable/disable help command
  enable-help-command: true


  ############################################################
  # +------------------------------------------------------+ #
  # |                      sCore Kits                      | #
  # +------------------------------------------------------+ #
  ############################################################

# Note: All items MUST be followed by a quantity!
# All kit names should be lower case, and will be treated as lower in permissions/costs.
# Syntax: - itemID[:DataValue/Durability] Amount [Enchantment:Level].. [itemmeta:value]...
# For Item Meta information visit http://wiki.ess3.net/wiki/Item_Meta
# 'delay' refers to the cooldown between how often you can use each kit, measured in seconds.
# Set delay to -1 for a one time kit.
# For more information, visit http://wiki.ess3.net/wiki/Kits

kits-options:

  # should the kits module be enabled or disabled?
  enable: true

  kits:
    tools:
      delay: 10
      items:
        - 272 1
        - 273 1
        - 274 1
        - 275 1
    dtools:
      delay: 600
      items:
        - 278 1 efficiency:1 durability:1 fortune:1 name:&4Gigadrill lore:The_drill_that_&npierces|the_heavens
        - 277 1 digspeed:3 name:Dwarf lore:Diggy|Diggy|Hole
        - 298 1 color:255,255,255 name:Top_Hat lore:Good_day,_Good_day
        - 279:780 1
    notch:
      delay: 6000
      items:
        - 397:3 1 player:Notch
    color:
      delay: 6000
      items:
        - 387 1 title:&4Book_&9o_&6Colors author:KHobbits lore:Ingame_color_codes book:Colors
    firework:
      delay: 6000
      items:
        - 401 1 name:Angry_Creeper color:red fade:green type:creeper power:1
        - 401 1 name:StarryNight color:yellow,orange fade:blue type:star effect:trail,twinkle power:1
        - 401 2 name:SolarWind color:yellow,orange fade:red shape:large effect:twinkle color:yellow,orange fade:red shape:ball effect:trail color:red,purple fade:pink shape:star effect:trail power:1


  ############################################################
  # +------------------------------------------------------+ #
  # |                     sCore Signs                      | #
  # +------------------------------------------------------+ #
  ############################################################

signs:

  # Essentials Sign Control
  # See http://wiki.ess3.net/wiki/Sign_Tutorial for instructions on how to use these.
  # To enable signs, remove # symbol. To disable all signs, comment/remove each sign.
  # Essentials colored sign support will be enabled when any sign types are enabled.
  # Color is not an actual sign, it's for enabling using color codes on signs, when the correct permissions are given.

  enabledSigns:
  #- color
  #- balance
  #- buy
  #- sell
  #- trade
  #- free
  #- disposal
  #- warp
  #- kit
  #- mail
  #- enchant
  #- gamemode
  #- heal
  #- info
  #- spawnmob
  #- repair
  #- time
  #- weather

  # How many times per second can Essentials signs be interacted with per player.
  # Values should be between 1-20, 20 being virtually no lag protection.
  # Lower numbers will reduce the possibility of lag, but may annoy players.
  sign-use-per-second: 4


  ############################################################
  # +------------------------------------------------------+ #
  # |                     sCore Warps                      | #
  # +------------------------------------------------------+ #
  ############################################################

warps:

  # should the warps module be enabled or disabled?
  enable: true

  # Set this true to enable permission per warp.
  per-warp-permission: false

  # Set this false if you want gui warps disable.
  gui-warps: true


  ############################################################
  # +------------------------------------------------------+ #
  # |                      sCore Homes                     | #
  # +------------------------------------------------------+ #
  ############################################################
homes:

  # should the homes module be enabled or disabled?
  enable: true

  # Allows people to set their bed at daytime.
  update-bed-at-daytime: true

  # Set to true to enable per-world permissions for using homes to teleport between worlds.
  # This applies to the /home only.
  # Give someone permission to teleport to a world with essentials.worlds.<worldname>
  world-home-permissions: false

  # Allow players to have multiple homes.
  # Players need essentials.sethome.multiple before they can have more than 1 home.
  # You can set the default number of multiple homes using the 'default' rank below.
  # To remove the home limit entirely, give people 'essentials.sethome.multiple.unlimited'.
  # To grant different home amounts to different people, you need to define a 'home-rank' below.
  # Create the 'home-rank' below, and give the matching permission: essentials.sethome.multiple.<home-rank>
  # For more information, visit http://wiki.ess3.net/wiki/Multihome
  sethome-multiple:
    default: 3
    vip: 5
    staff: 10

    # In this example someone with 'essentials.sethome.multiple' and 'essentials.sethome.multiple.vip' will have 5 homes.
    # Remember, they MUST have both permission nodes in order to be able to set multiple homes.

  # Set the timeout, in seconds for players to accept a tpa before the request is cancelled.
  # Set to 0 for no timeout.
  tpa-accept-cancellation: 120

  ############################################################
  # +------------------------------------------------------+ #
  # |                     sCore Eco                        | #
  # +------------------------------------------------------+ #
  ############################################################

economy:

  # should the eco module be enabled or disabled?
  enable: true

  # Defines the balance with which new players begin. Defaults to 0.
  starting-balance: 0

  # Defines the cost to use the given commands PER USE.
  # Some commands like /repair have sub-costs, check the wiki for more information.
  command-costs:
  # /example costs $1000 PER USE
  #example: 1000
  # /kit tools costs $1500 PER USE
  #kit-tools: 1500

  # Set this to a currency symbol you want to use.
  # Remember, if you want to use special characters in this document,
  # such as accented letters, you MUST save the file as UTF-8, not ANSI.
  currency-symbol: '$'

  # Set the maximum amount of money a player can have.
  # The amount is always limited to 10 trillion because of the limitations of a java double.
  max-money: 10000000000000

  # Set the minimum amount of money a player can have (must be above the negative of max-money).
  # Setting this to 0, will disable overdrafts/loans completely.
  min-money: -10000

  bank-starting-balance: 0

  # Set the maximum amount of money a player can have.
  # The amount is always limited to 10 trillion because of the limitations of a java double.
  max-bank: 10000000000000

  # Set the minimum amount of money a player can have (must be above the negative of max-money).
  # Setting this to 0, will disable overdrafts/loans completely.
  min-bank: -10000

  ############################################################
  # +------------------------------------------------------+ #
  # |                      sCore Chat                      | #
  # +------------------------------------------------------+ #
  ############################################################

chat:

  # should the chat module be enabled or disabled?
  enable: true

  # Chat formatting can be done in two ways, you can either define a standard format for all chat.
  # Or you can give a group specific chat format, to give some extra variation.
  # For more information of chat formatting, check out the wiki: http://wiki.ess3.net/wiki/Chat_Formatting

  format: '<{DISPLAYNAME}> {MESSAGE}'
  #format: '&7[{GROUP}]&r {DISPLAYNAME}&7:&r {MESSAGE}'

  group-formats:
  #  Default: '{WORLDNAME} {DISPLAYNAME}&7:&r {MESSAGE}'
  #  Admins: '{WORLDNAME} &c[{GROUP}]&r {DISPLAYNAME}&7:&c {MESSAGE}'

  # If you are using group formats make sure to remove the '#' to allow the setting to be read.

  chat-color-permission: 'score.chat.color'

  ############################################################
  # +------------------------------------------------------+ #
  # |            sCore Spawn / Join / New Players          | #
  # +------------------------------------------------------+ #
  ############################################################

newbies:

  # You can set a custom join message here, set to "none" to disable.
  # You may use color codes, use {USERNAME} the player's name or {PLAYER} for the player's displayname.
  custom-join-message: "none"

  # You can set a custom quit message here, set to "none" to disable.
  # You may use color codes, use {USERNAME} the player's name or {PLAYER} for the player's displayname.
  custom-quit-message: "none"

  # Should we announce to the server when someone logs in for the first time?
  # If so, use this format, replacing {DISPLAYNAME} with the player name.
  # If not, set to ''
  #announce-format: ''
  announce-format:
    - '&dWelcome {DISPLAYNAME}&d to the server!'

  # When we spawn for the first time, which spawnpoint do we use?
  # Set to "none" if you want to use the spawn point of the world.
  spawnpoint: newbies

  # Do we want to give users anything on first join? Set to '' to disable
  # This kit will be given regardless of cost and permissions, and will not trigger the kit delay.
  #kit: ''
  kit: tools

# Set this to lowest, if you want Multiverse to handle the respawning.
# Set this to high, if you want EssentialsSpawn to handle the respawning.
# Set this to highest, if you want to force EssentialsSpawn to handle the respawning.
respawn-listener-priority: high

# When users die, should they respawn at their first home or bed, instead of the spawnpoint?
respawn-at-home: false

  ############################################################
  # +------------------------------------------------------+ #
  # |                  sCore Chunk Limiter                 | #
  # +------------------------------------------------------+ #
  ############################################################

chunk-limiter:

  # Should sCore disable the chunk limiter completely?
  enable-chunk-limiter: true

  # What blocks should sCore limit per chunk?
  # Make sure all blocks stated here are correct enum materials, they can be found here:
  # (Latest MC Version) https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  # (1.12.2) https://helpch.at/docs/1.12.2/org/bukkit/Material.html
  # (1.8.8) https://helpch.at/docs/1.8.8/org/bukkit/Material.html
  blocks:
    HOPPER: 20
    MINECART: 5
    TNT_MINECART: 5
    ARMOR_STAND: 10
    CHEST: 30
    #ENDER_CHEST: 20