############################################################
# +------------------------------------------------------+ #
# |                    sCore Data                        | #
# +------------------------------------------------------+ #
############################################################

data:

  # should SCore cache data? this will optimize the amount of connections being used but will minimize db use across servers.
  cache-data: true

  # types: [H2 / SQLite(RECOMMENDED OVER H2) / MYSQL]
  type: 'SQLite'

  # The address for the database server.
  # - to enable this part, change type to 'MYSQL'
  # - some hosts can use your domain or server ip.
  address: 'host'
  # The standard DB engine port is used by default
  port: 3306
  # The name of the database to store tag data in.
  database: 'database'
  # Credentials for the database.
  username: 'user'
  password: 'pass'
  # leave this, if you don't know how to use options.
  options: 'useSSL=false&autoReconnect=true'
  # SSL is used to make connections more secure.
  useSSL: false